dist: xenial
language: python

python:
  - "2.7"
  - "3.6"
  - "3.7"

# command to install dependencies
install:
  - sudo apt-get update -qq
  - pip install -r requirements_dev.txt

# command to install dependencies
script:
  - python setup.py test

# Run code coverage
after_success: codecov

# Run on dev and master branches
branches:
  only:
    - master
